### ISSUE TITLE
How can we handle Authentication flows?

### ISSUE THREAD

**Issue by arslanakram** [kanzitelli/rn-navio#10]
Hi @kanzitelli,

First of all, great work! 

I've been trying to implement automatic redirection if user is authenticated but can't figure out how to do it?

If i'm assuming correctly (From React Navigation Docs: https://reactnavigation.org/docs/auth-flow) I need 2 instances of navio? 

I have the following in my **App.tsx**:
```
import 'expo-dev-client';
import React from 'react';
import * as Linking from 'expo-linking';
import { GestureHandlerRootView } from 'react-native-gesture-handler';
import { App, RootApp } from '@app/navio';
import { useAuth } from '@app/contexts/Auth';
import { getNavigationTheme } from '@app/utils/styleConfig/_react_native_ui_lib';

export default (): JSX.Element => {
    const { authData } = useAuth();
    return (
        <GestureHandlerRootView style={{ flex: 1 }}>
            {!authData ? (
                <RootApp
                    navigationContainerProps={{
                        theme: getNavigationTheme(),
                        linking: {
                            prefixes: [Linking.createURL('/auth/')],
                        },
                    }}
                />
            ) : (
                <App
                    navigationContainerProps={{
                        theme: getNavigationTheme(),
                        linking: {
                            prefixes: [Linking.createURL('/')],
                        },
                    }}
                />
            )}
        </GestureHandlerRootView>
    );
};

```
**navio.tsx**: (@app/navio)
```
import { Navio } from 'rn-navio';
import { useAppearance } from '@app/utils/hooks';
import { SignIn } from '@app/screens/SignInStack/SignIn';
import { SignUp } from '@app/screens/SignUpStack/SignUp';
import { Home } from '@app/screens/HomeStack/Home';

// App
export const navio = Navio.build({
    screens: {
        Home,
    },
    stacks: {
        HomeStack: {
            screens: ['Home'],
        },
    },
    root: 'HomeStack',
    hooks: [useAppearance],
});

// Root App
export const navioRoot = Navio.build({
    screens: {
        SignIn,
        SignUp,
    },
    stacks: {
        SignInStack: {
            screens: ['SignIn'],
        },
        SignUpStack: {
            screens: ['SignUp'],
        },
    },
    root: 'SignInStack',
    hooks: [useAppearance],
});

export const getNavio = () => navio;
export const App = navio.App;
export const RootApp = navioRoot.App;

```

This correctly renders the right Stack based on if user is authenticated or not but the navio methods don't work in my views, e.g.
```
        navio.push('SignUp', { type: 'pop' });
        navio.setRoot('stacks', 'SignUpStack');
```

The above methods work if i don't have 2 navio instances. So i'm wondering how to implement this.

Would highly appreciate any suggestions you could provide.

Thanks

**Comment by kanzitelli** [comment]
Hi @arslanakram! Thank you!

I have just added the Auth Flow into [expo-starter](https://github.com/kanzitelli/expo-starter). That example is based on a use case when the [login is successful](https://github.com/kanzitelli/expo-starter/blob/master/src/screens/auth/login.tsx#L38) and we just [call `navio.setRoot`](https://github.com/kanzitelli/expo-starter/blob/master/src/screens/auth/login.tsx#L43) for the desired app. Basically, this case is useful when you open your main app content from the beginning and need to open `SignIn` screen when press on `Login` button. 

If you want to automatically redirect to the desired flow (main app or auth) on app launch, the app layout would look like this

```tsx
// Navio layout
const navio = Navio.build({
  screens: { Main, SignIn, SignUp },
  stacks: {
    MainApp: ['Main'],
    Auth: ['SignIn', 'SignUp'],
  },
  
  // can be used as well but works in static way
  // root: 'MainApp',
});
const NavioApp = navio.App;

// Main app component
export default (): JSX.Element => {
    const { authData } = useAuth();
    const isLoggedIn = !!authData;

    return (
      <SomeProviders>
        <NavioApp initialRouteName={isLoggedIn ? 'MainApp' : 'Auth'} />
      </SomeProviders>
    );
}
```

You can use `initialRouteName` of `navio.App` to change root of the app as well setting `root` of `Navio.build` and using `navio.setRoot` during the app session. It's not well documented at the moment (but will be). You can read more about it [here](https://github.com/kanzitelli/rn-navio#root).

Let me know how it goes!

**Comment by arslanakram** [comment]
Perfect! This works!

Thanks for the quick response. 

Much appreciated!
