### ISSUE TITLE
Token of appreciation - Navio Logo

### ISSUE THREAD

**Issue by arslanakram** [kanzitelli/rn-navio#14]
Hi @kanzitelli,

Thank you for all the support and help. I run a software agency, [Pixelative](https://pixelative.co) and we just designed a logo for navio as a token of appreciation. 

Feel free to share any suggestions/changes you would like:

![navioa-v2-gradient-purple (1)](https://user-images.githubusercontent.com/8457398/226211278-92da542c-b290-46e0-9664-ccfbbd81bd46.jpg)

Thanks again.

**Comment by kanzitelli** [comment]
@arslanakram wow thank you so much! that's great!

The only thing I would change is the first letter to capitalised one ('n' --> 'N'). And I like the gradient colours!

I will add the logo as soon as I can!

**Comment by arslanakram** [comment]
@kanzitelli you're welcome!

Yeah we spent a while on finalizing the colors and drew a custom shape. I envision Navio to grow big in future. Wanted to make sure the branding was carefully thought of. 

Here's the revised one with capitalized N. 

![navio-gradient-purple-final](https://user-images.githubusercontent.com/8457398/226213980-dd62a9c2-5671-41db-8f57-323ed0d0d1d6.png)

Feel free to let me know if you need any revisions.

Also, would appreciate if you could credit us by adding Logo designed by [Pixelative](https://pixelative.co/) in your README.

Thanks,
