### ISSUE TITLE
Avoiding require cycles

### ISSUE THREAD

**Issue by nick-potts** [kanzitelli/rn-navio#18]
Given you have to import screens in the navio file, as well as export the navio instance for use in said screens, is there a trick to avoiding require cycles?

My cycle looks like this:
src/navio.tsx -> src/screens/chat.tsx -> src/services/index.tsx -> src/navio.tsx

**Comment by nick-potts** [comment]
I've found some documentation for a metro config line that does fix it. 
https://facebook.github.io/metro/docs/configuration/#requirecycleignorepatterns

I set mine to:
```config.resolver.requireCycleIgnorePatterns = [
  /(^|\/|\\)node_modules($|\/|\\)/,
  /^src\/navio.tsx$/,
];```

Unless there's a clean solution, it seems this is the best we've got.

**Comment by kanzitelli** [comment]
Hi @nick-potts! I've been always ignoring that issue as it didn't bring any problems, but it had to be fixed! Thank you, that works! I'll add that to docs.

**Comment by nick-potts** [comment]
No worries. Doesn't seem like the worst fix given the require cycle is bourne by the nav library importing the screens that instantiate the require cycle.
