### ISSUE TITLE
Allow passing route parameters to modals

### ISSUE THREAD

**Issue by lakardion** [kanzitelli/rn-navio#19]
Hello Kanzitelli. I'm loving navio since 0.0.1 !

Do you think we could allow modals to receive route parameters? Or is there already a way to do this? (btw tried `setParams` but did not understand fully how that should used for a modal screen)

I happened to require using a modal to confirm an action and to do it within the modal I needed some information (ig: ids)

I saw that with regular react navigation you could just pass params and the screen would receive that from `useRoute().params` 

Right now I'm using global state to pass the information to my modal but would definitely be really useful to just do:

```ts
navio.show('myModal', { usefulId: 'someid' } )
```

Similar to how `navio.push` signature is.

**Comment by kanzitelli** [comment]
Hey @lakardion! Happy to hear that! And I'm currently on the vacation, couldn't reply quickly.

Currently with navio it's possible but using react-navigation's instance `navio.N`. This is what you can do:
```
navio.N.navigate('MyModal', { screen: 'ScreenName', params: { usefulId: 'someid' }, });
```

Check out this [issue](https://github.com/kanzitelli/rn-navio/issues/20) for more info.

**Comment by lakardion** [comment]
Awesome. That is 100% what I needed. 

thank you very much. Cheers
