### ISSUE TITLE
`pushStack` with params

### ISSUE THREAD

**Issue by vndee** [kanzitelli/rn-navio#20]
Hi, thanks for your great work!

Currently, I have tried to use `navio.stacks.push('ChatStack', {userToken: userToken})` but it does not work. Can you help me on such navigating behavior like this. I can resolve this by set up the ChatScreen inside the current stack, but if I do that, I cannot hide the bottom tab bar in ChatScreen.

Thank you very much!

**Comment by danihorvath** [comment]
Just met with the same problem yesterday and solved it like this:

`navio.N.navigate('AuthorStack', {
          screen: 'Author',
          params: { author },
        });`

**Comment by vndee** [comment]
> Just met with the same problem yesterday and solved it like this:
> 
> `navio.N.navigate('AuthorStack', { screen: 'Author', params: { author }, });`

Thank you very much! It work as expected.
