### ISSUE TITLE
Updating the title of a screen

### ISSUE THREAD

**Issue by generalcss** [kanzitelli/rn-navio#23]
Hi,

How can you dynamically update the title for a screen in a stack? 
I did find updateOptions() for drawers and tabs. But not for screens. 

Any idea?

**Comment by kanzitelli** [comment]
Hi @generalcss! Navio doesn't support it at the moment, but as it's built on top of React Navigation, you can use `navigation.setOptions({ title: 'Title' })` ([docs](https://reactnavigation.org/docs/headers/#updating-options-with-setoptions)) and this [example](https://github.com/kanzitelli/expo-starter/blob/master/src/screens/main.tsx#L55C1-L55C1) as a reference. Let me know if it helps!

**Comment by generalcss** [comment]
Thanx, you helped me :). Know I know how to get to the react-navigation hooks
