### ISSUE TITLE
Compatibility Problem with Vexo Analytics

### ISSUE THREAD

**Issue by appsolut-jahn** [kanzitelli/rn-navio#27]
Vexo is a leading analytics platform for React Native apps. They promise to support any React Native app running the react-navigation router. We are using Navio based on react-navigation in our app, so we assumed to be on a good track. But now, when initializing Vexo, we get the error message:
`ERROR  TypeError: Cannot read property 'getRootState' of undefined`

Vexo told us, that "rn-navio exposes different APIs than expo-router and react-navigation, and therefore, it is not compatible with our tool".

Is there any option to make these components compatible, or do we just have to forgo Vexo Analytics?

**Comment by kanzitelli** [comment]
Hi there! Sorry for the late reply.

I haven't used Vexo analytics, however as Navio is fully built on top of React Navigation (you can see the code). Navio exposes pure React Navigation object via `navio.N`. Also, the API which Navio exposes is just a helpful syntax that calls `.navigate` method from React Navigation.
