### ISSUE TITLE
Modal with a parameter

### ISSUE THREAD

**Issue by Jay-Salisbury** [kanzitelli/rn-navio#28]
Any idea on how I can show a modal and pass it content string in a parameter? Using the starter app which is great but this particular use case isn't included and I'm at a bit of a loss as to whether there's an elegant way to do it.

**Comment by lakardion** [comment]
Hey I had asked this question earlier in the year. Do you think this helps your case?

https://github.com/kanzitelli/rn-navio/issues/19#issuecomment-1518709576

**Comment by Jay-Salisbury** [comment]
Sorry I didn't pick that up before, my bad. Thanks for the tip!

**Comment by kanzitelli** [comment]
Hi! You can find the solutions under [Passing params to a modal](https://github.com/kanzitelli/rn-navio?tab=readme-ov-file#passing-params-to-a-modal) section. With Navio `v0.1.0` you can use `navio.modals.show('ModalName', { data })`.
