### ISSUE TITLE
How is the start/home screen defined?

### ISSUE THREAD

**Issue by localjo** [kanzitelli/rn-navio#5]
This is not really an "issue". Would be better for "discussions", but that isn't enabled for this repo.

How can I define which screen is shown first when the app is opened? I don't see that mentioned in the documentation.

**Comment by localjo** [comment]
After some experimentation, it seems that the screen that is first shown changes based on the order of the items in `screens` or `tabs` passed into `Navio.build({ screens, tabs ])`. The order in `tabs` seems to override the order in `screens`, but the order of `screens` is used when no tabs are defined.

I thought this might be problematic since the order of object properties in JavaScript is not guaranteed, but it seems that [the order of object properties in JavaScript is actually predictable](https://www.stefanjudis.com/today-i-learned/property-order-is-predictable-in-javascript-objects-since-es2015/) these days.

**Comment by kanzitelli** [comment]
Hi @localjo! Thanks for bringing it up!

Yes, currently it does `Object.keys()` and the order is based on that. I was also concerned about the order of an object's keys in JS but it seemed to be working with no issues + your link as an evidence for that. But it has to be in the docs, that's right. So I will reopen the issue to keep track of that for the next version.
