### ISSUE TITLE
Is there a way to push a new stack and have a back arrow?

### ISSUE THREAD

**Issue by upanshed** [kanzitelli/rn-navio#7]
Is there a way to push a new stack or screen and have a back arrow in the top nav and the bottom tabs hidden?
Something like this
https://www.screencast.com/t/zI86iDMl5z

**Comment by kanzitelli** [comment]
Hi @upanshed! Yes, you can achieve it smooth with the newest Navio version `v0.0.5`. Your Navio layout will look somewhat like below:

```tsx
const navio = Navio.build({
  screens: {
    Main,
    Example,
    ProductPage: {
      component: Example,
      options: {
        headerShown: false,
      },
    },
  },
  stacks: {
    MainStack: ['Main', 'Example'],
    ProductPageStack: {
      screens: ['ProductPage'],
      containerOptions: {
        headerShown: true,
        title: 'Product page',
      },
    },
  },
  tabs: {
    AppTabs: {
      content: {
        MainTab: {
          stack: 'MainStack',
          options: () => ({
            title: 'Main',
          }),
        },
        PlaygroundTab: {
          stack: ['Example'],
          options: () => ({
            title: 'Playground',
          }),
        },
      },
    },
  },
  root: 'AppTabs',
});
```

And from any tabs' screen, you can do `navio.stacks.push('ProductPageStack')`. For more detailed example, check out [expo-starter/navio.tsx](https://github.com/kanzitelli/expo-starter/blob/master/src/navio.tsx).


https://user-images.githubusercontent.com/4402166/218905128-1a5b63ac-3d5b-418a-849a-00028a7f0acb.MP4

**Comment by upanshed** [comment]
That works great, thanks!
