### ISSUE TITLE
Hide tabbar on specific pages

### ISSUE THREAD

**Issue by nick-potts** [kanzitelli/rn-navio#9]
Is there a way to achieve this? https://reactnavigation.org/docs/hiding-tabbar-in-screens/

Tabs nested in a stack?

I'm trying to hide the tabbar on navigate. I achieved it with:
```MainTabs: {
      content: {
        MainTab: {
          stack: "HomeStack",
          options: (route) => ({
            title: "Main",
            tabBarStyle: {
              display: tabBarVisiblity(route),
            },
          }),
        },
      }
```

and 
```
function tabBarVisiblity(route: BaseOptionsProps): "flex" | "none" {
  if (!route?.route) return "flex";
  const routeName = getFocusedRouteNameFromRoute(route.route);
  if (routeName != "Home") {
    return "none";
  }
  return "flex";
}
```

but its not as good as native (long delay for the tabbar to show up after going back to the screen)

**Comment by kanzitelli** [comment]
Hey @nick-potts! Yes, you can easily achieve it with Navio (https://twitter.com/kanzitelli/status/1625673487217045505). The full example can be found @ [expo-starter](https://github.com/kanzitelli/expo-starter).

In Navio, all stacks, tabs, drawers, and modals are inside Navigator.Screen, so it's easy to navigate, set root or push them. For your use case, you will need to define a stack that you want to be pushed from tabs container (not showing tabs) and, of course, tabs. The code would look like below:

```tsx
const navio = Navio.build({
  screens: {
    Main,
    Settings,
    ProductPage: {
      component: Example,
      options: {
        headerShown: false,
      },
    },
  },
  stacks: {
    MainStack: ['Main', 'Example'],
    ProductPageStack: {
      screens: ['ProductPage'],
      containerOptions: {
        headerShown: true,
        title: 'Product page',
      },
    },
  },
  tabs: {
    AppTabs: {
      content: {
        MainTab: {
          stack: 'MainStack',
          options: () => ({
            title: 'Main',
          }),
        },
        SettingsTab: {
          stack: ['Settings'],
          options: () => ({
            title: 'Settings',
          }),
        },
      },
    },
  },
  root: 'AppTabs',
});

// you can push `ProductPageStack` from any point of your app
// https://github.com/kanzitelli/rn-navio#naviostackspushname
navio.stacks.push('ProductPageStack');
```

Let me know how it goes!

**Comment by nick-potts** [comment]
Hey, this worked but was a little hacky because I was unable to pass params to the new stack. Ended up using navio.N.navigate("ProductPageStack", params).
